name: Build & Push Shadcn Resizable Panels Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-shadcn-resizable-panels-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: shadcn-resizable-panels
            context: .
            file: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
          # platforms: linux/amd64,linux/arm64
